// This is automatically generated by the Tiger compiler.
// Do NOT modify!

extern void* prev;
//vtable structures declaration
struct BubbleSort_vtable;
struct BBS_vtable;
// structures
struct BubbleSort_class
{
  struct BubbleSort_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
struct BBS_class
{
  struct BBS_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
int * number;
int size;
};
// vtables structures
struct BubbleSort_vtable
{
char* BubbleSort_gc_map;
};

struct BBS_vtable
{
char* BBS_gc_map;
  int  (*Start)(struct BBS_class *this,int  sz);
  int  (*Sort)(struct BBS_class *this);
  int  (*Print)(struct BBS_class *this);
  int  (*Init)(struct BBS_class *this,int  sz);
};


// forward declare vtable
struct BubbleSort_vtable BubbleSort_vtable_; 
struct BBS_vtable BBS_vtable_; 
// methods
  struct BBS_Start_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct BBS_class * x_1;
  struct BBS_class * x_2;
  struct BBS_class * x_3;
  struct BBS_class * x_4;
};

int  BBS_Start(struct BBS_class * this, int  sz)
{
  struct BBS_Start_gc_frame frame;

  int aux01;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 4;
frame.x_1 = 0;
frame.x_2 = 0;
frame.x_3 = 0;
frame.x_4 = 0;

  aux01 = (frame.x_1=this, frame.x_1->vptr->Init(frame.x_1, sz));
  aux01 = (frame.x_2=this, frame.x_2->vptr->Print(frame.x_2));
  System_out_println (99999);
  aux01 = (frame.x_3=this, frame.x_3->vptr->Sort(frame.x_3));
  aux01 = (frame.x_4=this, frame.x_4->vptr->Print(frame.x_4));

  prev = frame.prev;

  return 0;
}
  struct BBS_Sort_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  BBS_Sort(struct BBS_class * this)
{
  struct BBS_Sort_gc_frame frame;

  int nt;
  int i;
  int aux02;
  int aux04;
  int aux05;
  int aux06;
  int aux07;
  int j;
  int t;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  i = this->size - 1;
  aux02 = 0 - 1;
  while((aux02) < (i))
  {
{
  j = 1;
  while((j) < (i + 1))
  {
{
  aux07 = j - 1;
  aux04 = this->number[aux07];
  aux05 = this->number[j];
  if ((aux05) < (aux04))
    {
{
    aux06 = j - 1;
    t = this->number[aux06];
  this->number[aux06] = this->number[j];
  this->number[j] = t;
}
    }

  else
    {
    nt = 0;
    }

  j = j + 1;
}
  }
  i = i - 1;
}
  }

  prev = frame.prev;

  return 0;
}
  struct BBS_Print_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  BBS_Print(struct BBS_class * this)
{
  struct BBS_Print_gc_frame frame;

  int j;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  j = 0;
  while((j) < (this->size))
  {
{
  System_out_println (this->number[j]);
  j = j + 1;
}
  }

  prev = frame.prev;

  return 0;
}
  struct BBS_Init_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  BBS_Init(struct BBS_class * this, int  sz)
{
  struct BBS_Init_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  this->size = sz;
  int *tempttt = (int*)Tiger_new_array (sz);
  this->number = tempttt;
  this->number[0] = 20;
  this->number[1] = 7;
  this->number[2] = 12;
  this->number[3] = 18;
  this->number[4] = 2;
  this->number[5] = 11;
  this->number[6] = 6;
  this->number[7] = 9;
  this->number[8] = 19;
  this->number[9] = 5;

  prev = frame.prev;

  return 0;
}

// vtables
struct BubbleSort_vtable BubbleSort_vtable_ = 
{
  ""
};

struct BBS_vtable BBS_vtable_ = 
{
  "10",
  BBS_Start,
  BBS_Sort,
  BBS_Print,
  BBS_Init
};


// main method
  struct main_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct BBS_class* x_0;
};
int Tiger_main ()
{
  struct main_gc_frame frame;

  prev = 0;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = 0;
  frame.locals_gc_count = 1;
  System_out_println ((frame.x_0=((struct BBS_class*)(Tiger_new (&BBS_vtable_, sizeof(struct BBS_class)/4 ))), frame.x_0->vptr->Start(frame.x_0, 10)));
}




