// This is automatically generated by the Tiger compiler.
// Do NOT modify!

extern void* prev;
//vtable structures declaration
struct LinearSearch_vtable;
struct LS_vtable;
// structures
struct LinearSearch_class
{
  struct LinearSearch_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
struct LS_class
{
  struct LS_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
int * number;
int size;
};
// vtables structures
struct LinearSearch_vtable
{
char* LinearSearch_gc_map;
};

struct LS_vtable
{
char* LS_gc_map;
  int  (*Start)(struct LS_class *this,int  sz);
  int  (*Print)(struct LS_class *this);
  int  (*Search)(struct LS_class *this,int  num);
  int  (*Init)(struct LS_class *this,int  sz);
};


// forward declare vtable
struct LinearSearch_vtable LinearSearch_vtable_; 
struct LS_vtable LS_vtable_; 
// methods
  struct LS_Start_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct LS_class * x_1;
  struct LS_class * x_2;
  struct LS_class * x_3;
  struct LS_class * x_4;
  struct LS_class * x_5;
  struct LS_class * x_6;
};

int  LS_Start(struct LS_class * this, int  sz)
{
  struct LS_Start_gc_frame frame;

  int aux01;
  int aux02;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 6;
frame.x_1 = 0;
frame.x_2 = 0;
frame.x_3 = 0;
frame.x_4 = 0;
frame.x_5 = 0;
frame.x_6 = 0;

  aux01 = (frame.x_1=this, frame.x_1->vptr->Init(frame.x_1, sz));
  aux02 = (frame.x_2=this, frame.x_2->vptr->Print(frame.x_2));
  System_out_println (9999);
  System_out_println ((frame.x_3=this, frame.x_3->vptr->Search(frame.x_3, 8)));
  System_out_println ((frame.x_4=this, frame.x_4->vptr->Search(frame.x_4, 12)));
  System_out_println ((frame.x_5=this, frame.x_5->vptr->Search(frame.x_5, 17)));
  System_out_println ((frame.x_6=this, frame.x_6->vptr->Search(frame.x_6, 50)));

  prev = frame.prev;

  return 55;
}
  struct LS_Print_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  LS_Print(struct LS_class * this)
{
  struct LS_Print_gc_frame frame;

  int j;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  j = 1;
  while((j) < (this->size))
  {
{
  System_out_println (this->number[j]);
  j = j + 1;
}
  }

  prev = frame.prev;

  return 0;
}
  struct LS_Search_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  LS_Search(struct LS_class * this, int  num)
{
  struct LS_Search_gc_frame frame;

  int j;
  int ls01;
  int ifound;
  int aux01;
  int aux02;
  int nt;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  j = 1;
  ls01 = 0;
  ifound = 0;
  while((j) < (this->size))
  {
{
  aux01 = this->number[j];
  aux02 = num + 1;
  if ((aux01) < (num))
    {
    nt = 0;
    }

  else
    {
    if (!((aux01) < (aux02)))
      {
      nt = 0;
      }

    else
      {
{
      ls01 = 1;
      ifound = 1;
      j = this->size;
}
      }

    }

  j = j + 1;
}
  }

  prev = frame.prev;

  return ifound;
}
  struct LS_Init_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  LS_Init(struct LS_class * this, int  sz)
{
  struct LS_Init_gc_frame frame;

  int j;
  int k;
  int aux01;
  int aux02;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  this->size = sz;
  int *tempttt = (int*)Tiger_new_array (sz);
  this->number = tempttt;
  j = 1;
  k = this->size + 1;
  while((j) < (this->size))
  {
{
  aux01 = 2 * j;
  aux02 = k - 3;
  this->number[j] = aux01 + aux02;
  j = j + 1;
  k = k - 1;
}
  }

  prev = frame.prev;

  return 0;
}

// vtables
struct LinearSearch_vtable LinearSearch_vtable_ = 
{
  ""
};

struct LS_vtable LS_vtable_ = 
{
  "10",
  LS_Start,
  LS_Print,
  LS_Search,
  LS_Init
};


// main method
  struct main_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct LS_class* x_0;
};
int Tiger_main ()
{
  struct main_gc_frame frame;

  prev = 0;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = 0;
  frame.locals_gc_count = 1;
  System_out_println ((frame.x_0=((struct LS_class*)(Tiger_new (&LS_vtable_, sizeof(struct LS_class)/4 ))), frame.x_0->vptr->Start(frame.x_0, 10)));
}




