// This is automatically generated by the Tiger compiler.
// Do NOT modify!

extern void* prev;
//vtable structures declaration
struct LinkedList_vtable;
struct Element_vtable;
struct List_vtable;
struct LL_vtable;
// structures
struct LinkedList_class
{
  struct LinkedList_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
struct Element_class
{
  struct Element_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
int Age;
int Salary;
int Married;
};
struct List_class
{
  struct List_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
struct Element_class *elem;
struct List_class *next;
int end;
};
struct LL_class
{
  struct LL_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
// vtables structures
struct LinkedList_vtable
{
char* LinkedList_gc_map;
};

struct Element_vtable
{
char* Element_gc_map;
  int  (*Init)(struct Element_class *this,int  v_Age,int  v_Salary,int  v_Married);
  int  (*GetAge)(struct Element_class *this);
  int  (*GetSalary)(struct Element_class *this);
  int  (*GetMarried)(struct Element_class *this);
  int  (*Equal)(struct Element_class *this,struct Element_class * other);
  int  (*Compare)(struct Element_class *this,int  num1,int  num2);
};

struct List_vtable
{
char* List_gc_map;
  int  (*Init)(struct List_class *this);
  int  (*InitNew)(struct List_class *this,struct Element_class * v_elem,struct List_class * v_next,int  v_end);
  struct List_class * (*Insert)(struct List_class *this,struct Element_class * new_elem);
  int  (*SetNext)(struct List_class *this,struct List_class * v_next);
  struct List_class * (*Delete)(struct List_class *this,struct Element_class * e);
  int  (*Search)(struct List_class *this,struct Element_class * e);
  int  (*GetEnd)(struct List_class *this);
  struct Element_class * (*GetElem)(struct List_class *this);
  struct List_class * (*GetNext)(struct List_class *this);
  int  (*Print)(struct List_class *this);
};

struct LL_vtable
{
char* LL_gc_map;
  int  (*Start)(struct LL_class *this);
};


// forward declare vtable
struct LinkedList_vtable LinkedList_vtable_; 
struct Element_vtable Element_vtable_; 
struct List_vtable List_vtable_; 
struct LL_vtable LL_vtable_; 
// methods
  struct Element_Init_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Element_Init(struct Element_class * this, int  v_Age, int  v_Salary, int  v_Married)
{
  struct Element_Init_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "000";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  this->Age = v_Age;
  this->Salary = v_Salary;
  this->Married = v_Married;

  prev = frame.prev;

  return (int)(1);
}
  struct Element_GetAge_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Element_GetAge(struct Element_class * this)
{
  struct Element_GetAge_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;


  prev = frame.prev;

  return this->Age;
}
  struct Element_GetSalary_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Element_GetSalary(struct Element_class * this)
{
  struct Element_GetSalary_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;


  prev = frame.prev;

  return this->Salary;
}
  struct Element_GetMarried_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Element_GetMarried(struct Element_class * this)
{
  struct Element_GetMarried_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;


  prev = frame.prev;

  return (int)(this->Married);
}
  struct Element_Equal_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct Element_class * x_1;
  struct Element_class * x_2;
  struct Element_class * x_3;
  struct Element_class * x_4;
  struct Element_class * x_5;
  struct Element_class * x_6;
};

int  Element_Equal(struct Element_class * this, struct Element_class * other)
{
  struct Element_Equal_gc_frame frame;

  int ret_val;
  int aux01;
  int aux02;
  int nt;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "1";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 6;
frame.x_1 = 0;
frame.x_2 = 0;
frame.x_3 = 0;
frame.x_4 = 0;
frame.x_5 = 0;
frame.x_6 = 0;

  ret_val = 1;
  aux01 = (frame.x_1=other, frame.x_1->vptr->GetAge(frame.x_1));
  if (!((frame.x_2=this, frame.x_2->vptr->Compare(frame.x_2, aux01, this->Age))))
    {
    ret_val = 0;
    }

  else
    {
{
    aux02 = (frame.x_3=other, frame.x_3->vptr->GetSalary(frame.x_3));
    if (!((frame.x_4=this, frame.x_4->vptr->Compare(frame.x_4, aux02, this->Salary))))
      {
      ret_val = 0;
      }

    else
      {
      if (this->Married)
        {
        if (!((frame.x_5=other, frame.x_5->vptr->GetMarried(frame.x_5))))
          {
          ret_val = 0;
          }

        else
          {
          nt = 0;
          }

        }

      else
        {
        if ((frame.x_6=other, frame.x_6->vptr->GetMarried(frame.x_6)))
          {
          ret_val = 0;
          }

        else
          {
          nt = 0;
          }

        }

      }

}
    }


  prev = frame.prev;

  return (int)(ret_val);
}
  struct Element_Compare_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Element_Compare(struct Element_class * this, int  num1, int  num2)
{
  struct Element_Compare_gc_frame frame;

  int retval;
  int aux02;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "00";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  retval = 0;
  aux02 = num2 + 1;
  if ((num1) < (num2))
    {
    retval = 0;
    }

  else
    {
    if (!((num1) < (aux02)))
      {
      retval = 0;
      }

    else
      {
      retval = 1;
      }

    }


  prev = frame.prev;

  return (int)(retval);
}
  struct List_Init_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  List_Init(struct List_class * this)
{
  struct List_Init_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  this->end = 1;

  prev = frame.prev;

  return (int)(1);
}
  struct List_InitNew_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  List_InitNew(struct List_class * this, struct Element_class * v_elem, struct List_class * v_next, int  v_end)
{
  struct List_InitNew_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "110";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  this->end = v_end;
  Interceptor(this->elem , v_elem);
  this->elem = v_elem;
  Interceptor(this->next , v_next);
  this->next = v_next;

  prev = frame.prev;

  return (int)(1);
}
  struct List_Insert_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct List_class * aux03;
  struct List_class * aux02;
  struct List_class * x_7;
};

struct List_class * List_Insert(struct List_class * this, struct Element_class * new_elem)
{
  struct List_Insert_gc_frame frame;

  int ret_val;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "1";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 3;
frame.aux03 = 0;
frame.aux02 = 0;
frame.x_7 = 0;

  frame.aux03 = this;
  frame.aux02 = ((struct List_class*)(Tiger_new (&List_vtable_, sizeof(struct List_class)/4 )));
  ret_val = (frame.x_7=frame.aux02, frame.x_7->vptr->InitNew(frame.x_7, new_elem, frame.aux03, 0));

  prev = frame.prev;

  return frame.aux02;
}
  struct List_SetNext_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  List_SetNext(struct List_class * this, struct List_class * v_next)
{
  struct List_SetNext_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "1";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  Interceptor(this->next , v_next);
  this->next = v_next;

  prev = frame.prev;

  return (int)(1);
}
  struct List_Delete_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct List_class * my_head;
  struct List_class * aux01;
  struct List_class * prevv;
  struct Element_class * var_elem;
  struct Element_class * x_8;
  struct List_class * x_9;
  struct List_class * x_10;
  struct List_class * x_11;
  struct List_class * x_12;
  struct List_class * x_13;
  struct List_class * x_14;
};

struct List_class * List_Delete(struct List_class * this, struct Element_class * e)
{
  struct List_Delete_gc_frame frame;

  int ret_val;
  int aux05;
  int var_end;
  int aux04;
  int nt;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "1";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 11;
frame.my_head = 0;
frame.aux01 = 0;
frame.prevv = 0;
frame.var_elem = 0;
frame.x_8 = 0;
frame.x_9 = 0;
frame.x_10 = 0;
frame.x_11 = 0;
frame.x_12 = 0;
frame.x_13 = 0;
frame.x_14 = 0;

  frame.my_head = this;
  ret_val = 0;
  aux04 = 0 - 1;
  frame.aux01 = this;
  frame.prevv = this;
  var_end = this->end;
  Interceptor(frame.var_elem , this->elem);
  frame.var_elem = this->elem;
  while((!(var_end)) && (!(ret_val)))
  {
{
  if ((frame.x_8=e, frame.x_8->vptr->Equal(frame.x_8, frame.var_elem)))
    {
{
    ret_val = 1;
    if ((aux04) < (0))
      {
{
      struct List *temp_x_9;
      temp_x_9 = (frame.x_9=frame.aux01, frame.x_9->vptr->GetNext(frame.x_9));
      Interceptor(frame.my_head , temp_x_9);
      frame.my_head = temp_x_9;
}
      }

    else
      {
{
      System_out_println (0 - 555);
      aux05 = (frame.x_10=frame.prevv, frame.x_10->vptr->SetNext(frame.x_10, (frame.x_11=frame.aux01, frame.x_11->vptr->GetNext(frame.x_11))));
      System_out_println (0 - 555);
}
      }

}
    }

  else
    {
    nt = 0;
    }

  if (!(ret_val))
    {
{
    Interceptor(frame.prevv , frame.aux01);
    frame.prevv = frame.aux01;
    struct List *temp_x_12;
    temp_x_12 = (frame.x_12=frame.aux01, frame.x_12->vptr->GetNext(frame.x_12));
    Interceptor(frame.aux01 , temp_x_12);
    frame.aux01 = temp_x_12;
    var_end = (frame.x_13=frame.aux01, frame.x_13->vptr->GetEnd(frame.x_13));
    struct Element *temp_x_14;
    temp_x_14 = (frame.x_14=frame.aux01, frame.x_14->vptr->GetElem(frame.x_14));
    Interceptor(frame.var_elem , temp_x_14);
    frame.var_elem = temp_x_14;
    aux04 = 1;
}
    }

  else
    {
    nt = 0;
    }

}
  }

  prev = frame.prev;

  return frame.my_head;
}
  struct List_Search_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct List_class * aux01;
  struct Element_class * var_elem;
  struct Element_class * x_15;
  struct List_class * x_16;
  struct List_class * x_17;
  struct List_class * x_18;
};

int  List_Search(struct List_class * this, struct Element_class * e)
{
  struct List_Search_gc_frame frame;

  int int_ret_val;
  int var_end;
  int nt;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "1";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 6;
frame.aux01 = 0;
frame.var_elem = 0;
frame.x_15 = 0;
frame.x_16 = 0;
frame.x_17 = 0;
frame.x_18 = 0;

  int_ret_val = 0;
  frame.aux01 = this;
  var_end = this->end;
  Interceptor(frame.var_elem , this->elem);
  frame.var_elem = this->elem;
  while(!(var_end))
  {
{
  if ((frame.x_15=e, frame.x_15->vptr->Equal(frame.x_15, frame.var_elem)))
    {
{
    int_ret_val = 1;
}
    }

  else
    {
    nt = 0;
    }

  struct List *temp_x_16;
  temp_x_16 = (frame.x_16=frame.aux01, frame.x_16->vptr->GetNext(frame.x_16));
  Interceptor(frame.aux01 , temp_x_16);
  frame.aux01 = temp_x_16;
  var_end = (frame.x_17=frame.aux01, frame.x_17->vptr->GetEnd(frame.x_17));
  struct Element *temp_x_18;
  temp_x_18 = (frame.x_18=frame.aux01, frame.x_18->vptr->GetElem(frame.x_18));
  Interceptor(frame.var_elem , temp_x_18);
  frame.var_elem = temp_x_18;
}
  }

  prev = frame.prev;

  return int_ret_val;
}
  struct List_GetEnd_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  List_GetEnd(struct List_class * this)
{
  struct List_GetEnd_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;


  prev = frame.prev;

  return (int)(this->end);
}
  struct List_GetElem_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

struct Element_class * List_GetElem(struct List_class * this)
{
  struct List_GetElem_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;


  prev = frame.prev;

  return this->elem;
}
  struct List_GetNext_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

struct List_class * List_GetNext(struct List_class * this)
{
  struct List_GetNext_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;


  prev = frame.prev;

  return this->next;
}
  struct List_Print_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct List_class * aux01;
  struct Element_class * var_elem;
  struct Element_class * x_19;
  struct List_class * x_20;
  struct List_class * x_21;
  struct List_class * x_22;
};

int  List_Print(struct List_class * this)
{
  struct List_Print_gc_frame frame;

  int var_end;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 6;
frame.aux01 = 0;
frame.var_elem = 0;
frame.x_19 = 0;
frame.x_20 = 0;
frame.x_21 = 0;
frame.x_22 = 0;

  frame.aux01 = this;
  var_end = this->end;
  Interceptor(frame.var_elem , this->elem);
  frame.var_elem = this->elem;
  while(!(var_end))
  {
{
  System_out_println ((frame.x_19=frame.var_elem, frame.x_19->vptr->GetAge(frame.x_19)));
  struct List *temp_x_20;
  temp_x_20 = (frame.x_20=frame.aux01, frame.x_20->vptr->GetNext(frame.x_20));
  Interceptor(frame.aux01 , temp_x_20);
  frame.aux01 = temp_x_20;
  var_end = (frame.x_21=frame.aux01, frame.x_21->vptr->GetEnd(frame.x_21));
  struct Element *temp_x_22;
  temp_x_22 = (frame.x_22=frame.aux01, frame.x_22->vptr->GetElem(frame.x_22));
  Interceptor(frame.var_elem , temp_x_22);
  frame.var_elem = temp_x_22;
}
  }

  prev = frame.prev;

  return (int)(1);
}
  struct LL_Start_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct List_class * head;
  struct List_class * last_elem;
  struct Element_class * el01;
  struct Element_class * el02;
  struct Element_class * el03;
  struct List_class * x_23;
  struct List_class * x_24;
  struct List_class * x_25;
  struct Element_class * x_26;
  struct List_class * x_27;
  struct List_class * x_28;
  struct Element_class * x_29;
  struct List_class * x_30;
  struct List_class * x_31;
  struct Element_class * x_32;
  struct List_class * x_33;
  struct List_class * x_34;
  struct Element_class * x_35;
  struct List_class * x_36;
  struct List_class * x_37;
  struct Element_class * x_38;
  struct List_class * x_39;
  struct List_class * x_40;
  struct List_class * x_41;
  struct List_class * x_42;
  struct List_class * x_43;
  struct List_class * x_44;
};

int  LL_Start(struct LL_class * this)
{
  struct LL_Start_gc_frame frame;

  int aux01;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 27;
frame.head = 0;
frame.last_elem = 0;
frame.el01 = 0;
frame.el02 = 0;
frame.el03 = 0;
frame.x_23 = 0;
frame.x_24 = 0;
frame.x_25 = 0;
frame.x_26 = 0;
frame.x_27 = 0;
frame.x_28 = 0;
frame.x_29 = 0;
frame.x_30 = 0;
frame.x_31 = 0;
frame.x_32 = 0;
frame.x_33 = 0;
frame.x_34 = 0;
frame.x_35 = 0;
frame.x_36 = 0;
frame.x_37 = 0;
frame.x_38 = 0;
frame.x_39 = 0;
frame.x_40 = 0;
frame.x_41 = 0;
frame.x_42 = 0;
frame.x_43 = 0;
frame.x_44 = 0;

  frame.last_elem = ((struct List_class*)(Tiger_new (&List_vtable_, sizeof(struct List_class)/4 )));
  aux01 = (frame.x_23=frame.last_elem, frame.x_23->vptr->Init(frame.x_23));
  Interceptor(frame.head , frame.last_elem);
  frame.head = frame.last_elem;
  aux01 = (frame.x_24=frame.head, frame.x_24->vptr->Init(frame.x_24));
  aux01 = (frame.x_25=frame.head, frame.x_25->vptr->Print(frame.x_25));
  frame.el01 = ((struct Element_class*)(Tiger_new (&Element_vtable_, sizeof(struct Element_class)/4 )));
  aux01 = (frame.x_26=frame.el01, frame.x_26->vptr->Init(frame.x_26, 25, 37000, 0));
  struct List *temp_x_27;
  temp_x_27 = (frame.x_27=frame.head, frame.x_27->vptr->Insert(frame.x_27, frame.el01));
  Interceptor(frame.head , temp_x_27);
  frame.head = temp_x_27;
  aux01 = (frame.x_28=frame.head, frame.x_28->vptr->Print(frame.x_28));
  System_out_println (10000000);
  frame.el01 = ((struct Element_class*)(Tiger_new (&Element_vtable_, sizeof(struct Element_class)/4 )));
  aux01 = (frame.x_29=frame.el01, frame.x_29->vptr->Init(frame.x_29, 39, 42000, 1));
  Interceptor(frame.el02 , frame.el01);
  frame.el02 = frame.el01;
  struct List *temp_x_30;
  temp_x_30 = (frame.x_30=frame.head, frame.x_30->vptr->Insert(frame.x_30, frame.el01));
  Interceptor(frame.head , temp_x_30);
  frame.head = temp_x_30;
  aux01 = (frame.x_31=frame.head, frame.x_31->vptr->Print(frame.x_31));
  System_out_println (10000000);
  frame.el01 = ((struct Element_class*)(Tiger_new (&Element_vtable_, sizeof(struct Element_class)/4 )));
  aux01 = (frame.x_32=frame.el01, frame.x_32->vptr->Init(frame.x_32, 22, 34000, 0));
  struct List *temp_x_33;
  temp_x_33 = (frame.x_33=frame.head, frame.x_33->vptr->Insert(frame.x_33, frame.el01));
  Interceptor(frame.head , temp_x_33);
  frame.head = temp_x_33;
  aux01 = (frame.x_34=frame.head, frame.x_34->vptr->Print(frame.x_34));
  frame.el03 = ((struct Element_class*)(Tiger_new (&Element_vtable_, sizeof(struct Element_class)/4 )));
  aux01 = (frame.x_35=frame.el03, frame.x_35->vptr->Init(frame.x_35, 27, 34000, 0));
  System_out_println ((frame.x_36=frame.head, frame.x_36->vptr->Search(frame.x_36, frame.el02)));
  System_out_println ((frame.x_37=frame.head, frame.x_37->vptr->Search(frame.x_37, frame.el03)));
  System_out_println (10000000);
  frame.el01 = ((struct Element_class*)(Tiger_new (&Element_vtable_, sizeof(struct Element_class)/4 )));
  aux01 = (frame.x_38=frame.el01, frame.x_38->vptr->Init(frame.x_38, 28, 35000, 0));
  struct List *temp_x_39;
  temp_x_39 = (frame.x_39=frame.head, frame.x_39->vptr->Insert(frame.x_39, frame.el01));
  Interceptor(frame.head , temp_x_39);
  frame.head = temp_x_39;
  aux01 = (frame.x_40=frame.head, frame.x_40->vptr->Print(frame.x_40));
  System_out_println (2220000);
  struct List *temp_x_41;
  temp_x_41 = (frame.x_41=frame.head, frame.x_41->vptr->Delete(frame.x_41, frame.el02));
  Interceptor(frame.head , temp_x_41);
  frame.head = temp_x_41;
  aux01 = (frame.x_42=frame.head, frame.x_42->vptr->Print(frame.x_42));
  System_out_println (33300000);
  struct List *temp_x_43;
  temp_x_43 = (frame.x_43=frame.head, frame.x_43->vptr->Delete(frame.x_43, frame.el01));
  Interceptor(frame.head , temp_x_43);
  frame.head = temp_x_43;
  aux01 = (frame.x_44=frame.head, frame.x_44->vptr->Print(frame.x_44));
  System_out_println (44440000);

  prev = frame.prev;

  return 0;
}

// vtables
struct LinkedList_vtable LinkedList_vtable_ = 
{
  ""
};

struct Element_vtable Element_vtable_ = 
{
  "000",
  Element_Init,
  Element_GetAge,
  Element_GetSalary,
  Element_GetMarried,
  Element_Equal,
  Element_Compare
};

struct List_vtable List_vtable_ = 
{
  "110",
  List_Init,
  List_InitNew,
  List_Insert,
  List_SetNext,
  List_Delete,
  List_Search,
  List_GetEnd,
  List_GetElem,
  List_GetNext,
  List_Print
};

struct LL_vtable LL_vtable_ = 
{
  "",
  LL_Start
};


// main method
  struct main_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct LL_class* x_0;
};
int Tiger_main ()
{
  struct main_gc_frame frame;

  prev = 0;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = 0;
  frame.locals_gc_count = 1;
  System_out_println ((frame.x_0=((struct LL_class*)(Tiger_new (&LL_vtable_, sizeof(struct LL_class)/4 ))), frame.x_0->vptr->Start(frame.x_0)));
}




