// This is automatically generated by the Tiger compiler.
// Do NOT modify!

extern void* prev;
//vtable structures declaration
struct Factorial_vtable;
struct Memery220_vtable;
struct Fac_vtable;
// structures
struct Factorial_class
{
  struct Factorial_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
struct Memery220_class
{
  struct Memery220_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
int * c;
};
struct Fac_class
{
  struct Fac_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
// vtables structures
struct Factorial_vtable
{
char* Factorial_gc_map;
};

struct Memery220_vtable
{
char* Memery220_gc_map;
  int  (*fun)(struct Memery220_class *this);
};

struct Fac_vtable
{
char* Fac_gc_map;
  int  (*ComputeFac)(struct Fac_class *this,int  num);
};


// forward declare vtable
struct Factorial_vtable Factorial_vtable_; 
struct Memery220_vtable Memery220_vtable_; 
struct Fac_vtable Fac_vtable_; 
// methods
  struct Memery220_fun_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Memery220_fun(struct Memery220_class * this)
{
  struct Memery220_fun_gc_frame frame;

  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  int *tempttt = (int*)Tiger_new_array (50);
  this->c = tempttt;

  prev = frame.prev;

  return 919191;
}
  struct Fac_ComputeFac_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct Memery220_class * a;
  struct Memery220_class * x_1;
};

int  Fac_ComputeFac(struct Fac_class * this, int  num)
{
  struct Fac_ComputeFac_gc_frame frame;

  int c;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 2;
frame.a = 0;
frame.x_1 = 0;

  while(1)
  {
{
  frame.a = ((struct Memery220_class*)(Tiger_new (&Memery220_vtable_, sizeof(struct Memery220_class)/4 )));
  c = (frame.x_1=frame.a, frame.x_1->vptr->fun(frame.x_1));
  System_out_println (c);
}
  }
  System_out_println (42);

  prev = frame.prev;

  return 9999;
}

// vtables
struct Factorial_vtable Factorial_vtable_ = 
{
  ""
};

struct Memery220_vtable Memery220_vtable_ = 
{
  "1",
  Memery220_fun
};

struct Fac_vtable Fac_vtable_ = 
{
  "",
  Fac_ComputeFac
};


// main method
  struct main_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct Fac_class* x_0;
};
int Tiger_main ()
{
  struct main_gc_frame frame;

  prev = NULL;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = 0;
  frame.locals_gc_count = 1;
  System_out_println ((frame.x_0=((struct Fac_class*)(Tiger_new (&Fac_vtable_, sizeof(struct Fac_class)/4 ))), frame.x_0->vptr->ComputeFac(frame.x_0, 10)));
}




