// This is automatically generated by the Tiger compiler.
// Do NOT modify!

extern void* prev;
//vtable structures declaration
struct Sum_vtable;
struct Doit_vtable;
// structures
struct Sum_class
{
  struct Sum_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
struct Doit_class
{
  struct Doit_vtable *vptr;
int isObjOrArray;
void *forwarding;
unsigned mark;
};
// vtables structures
struct Sum_vtable
{
char* Sum_gc_map;
};

struct Doit_vtable
{
char* Doit_gc_map;
  int  (*doit)(struct Doit_class *this,int  n);
};


// forward declare vtable
struct Sum_vtable Sum_vtable_; 
struct Doit_vtable Doit_vtable_; 
// methods
  struct Doit_doit_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
};

int  Doit_doit(struct Doit_class * this, int  n)
{
  struct Doit_doit_gc_frame frame;

  int sum;
  int i;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "0";
  frame.arguments_base_address = (int*)&this;
  frame.locals_gc_count = 0;

  i = 1;
  sum = 0;
  while((i) < (n))
  {
{
  sum = sum + i;
  i = i + 1;
}
  }

  prev = frame.prev;

  return sum;
}

// vtables
struct Sum_vtable Sum_vtable_ = 
{
  ""
};

struct Doit_vtable Doit_vtable_ = 
{
  "",
  Doit_doit
};


// main method
  struct main_gc_frame
{
  void *prev;
  char *arguments_gc_map;
  int *arguments_base_address;
  int locals_gc_count;
  struct Doit_class* x_0;
};
int Tiger_main ()
{
  struct main_gc_frame frame;

  prev = NULL;
  frame.prev = prev;
  prev = &frame;
  frame.arguments_gc_map = "";
  frame.arguments_base_address = 0;
  frame.locals_gc_count = 1;
  System_out_println ((frame.x_0=((struct Doit_class*)(Tiger_new (&Doit_vtable_, sizeof(struct Doit_class)/4 ))), frame.x_0->vptr->doit(frame.x_0, 101)));
}




