; This is automatically generated by the Tiger compiler.
; Do NOT modify!

.class public Doit
.super java/lang/Object

.field public it Lbase;
.method public <init>()V
    aload 0
    invokespecial java/lang/Object/<init>()V
    return
.end method


.method public doit(I)I
.limit stack 4096
.limit locals 3
    ldc 1
    ireturn
.end method
.method public ff(LDoit;)I
.limit stack 4096
.limit locals 3
    ldc 1000
    ireturn
.end method
